### ISSUE TITLE
Tests are flapping

### ISSUE THREAD

**Issue by AlexDaniel** [tony-o/perl6-flow#7]
When running the tests in a loop like this:
```bash
while PERL6LIB=lib/ prove --exec=perl6 t/*.t; do :; done
```

I got this result:
```
t/00-Test.t .. ok   
t/01-TAP.t ... ok   
t/02-test.t .. No such method 'passed' for invocant of type 'Any'
  in block <unit> at t/02-test.t line 17

t/02-test.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 3/3 subtests 

Test Summary Report
-------------------
t/02-test.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 3 tests but ran 0.
```

**Comment by tony-o** [comment]
@AlexDaniel what p6 version is this?  I'm not able to reproduce on blead `This is Rakudo version 2018.06-190-g925c11343 built on MoarVM version 2018.06-223-ga50a0b15b implementing Perl 6.c.`

**Comment by AlexDaniel** [comment]
@tony-o can reproduce on 2018.05 and also on HEAD.

**Comment by tony-o** [comment]
What OS?  No luck on HEAD for me

Sent from my iPhone

On Jul 16, 2018, at 12:04 AM, Aleks-Daniel Jakimenko-Aleksejev <notifications@github.com<mailto:notifications@github.com>> wrote:


@tony-o<https://github.com/tony-o> can reproduce on 2018.05 and also on HEAD.

**Comment by AlexDaniel** [comment]
@tony-o linux. Are you running it in a loop like I mentioned? If yes, can you try loading your cpu with some other tasks (so that the tests are running while the system is under load)?

**Comment by tony-o** [comment]
I am running it in a loop on latest, was watching a movie and load testing a database while it ran.  I’ll put it on a vm and give it a test (I’m on OS X)

Sent from my iPhone

On Jul 15, 2018, at 11:09 PM, Aleks-Daniel Jakimenko-Aleksejev <notifications@github.com<mailto:notifications@github.com>> wrote:


@tony-o<https://github.com/tony-o> linux. Are you running it in a loop like I mentioned? If yes, can you try loading your cpu with some other tasks (so that the tests are running while the system is under load)?

**Comment by tony-o** [comment]
@AlexDaniel even on debian and `stress --cpu 8` running during the loop, i ran through 13,000 iterations with 0 failures ..
